resources:
  - name: mgit
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bmicro\/.+\b
        
  - name: tgit
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \btemplate\/.+\b

  - name: folder1
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder1\/.+\b

  - name: folder2
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder2\/.+\b


  - name: folder3
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder3\/.+\b

  - name: folder4
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder4\/.+\b

  - name: folder5
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder4\/.+\b

  - name: folder6
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder4\/.+\b


  - name: folder7
    type: GitRepo
    configuration:
      path: kashyaprahul94/test-jfrog-pipelines
      branches:
        include: ^{{gitBranch}}$
      gitProvider: github_kashyaprahul94
      files:
        include: \bfolder4\/.+\b

  - name: m1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m2
    type: PropertyBag
    configuration:
      key1: value1

  - name: m3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m4
    type: PropertyBag
    configuration:
      key1: value1


  - name: m5
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m6
    type: PropertyBag
    configuration:
      key1: value1

  - name: m7
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m8
    type: PropertyBag
    configuration:
      key1: value1


  - name: m9
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m10
    type: PropertyBag
    configuration:
      key1: value1

  - name: m11
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2

  - name: m12
    type: PropertyBag
    configuration:
      key1: value1
pipelines:
  - name: BugPipeline2
    steps:
      - name: start
        type: Bash
        execution: 
          onExecute:
            - echo "KICKOFF"

      - name: template_build
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: tgit
          affinityGroup: group1
          outputResources:
            - name: m1
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"

      - name: folder1_build
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: folder1
          affinityGroup: group1
          outputResources:
            - name: m1
            - name: m6
            - name: m5
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m5 "date1=$date"
            - write_output m6 "date1=$date"


      - name: folder2_build
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: folder2
          affinityGroup: group1
          outputResources:
            - name: m1
            - name: m8
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m1 "date1=$date"
            - write_output m8 "date1=$date"


      - name: folder3_build
        type: Bash
        configuration:
          inputSteps:
            - name: start
          inputResources:
            - name: folder3
          affinityGroup: group1
          outputResources:
            - name: m1
            - name: m7
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            # - write_output m1 "date1=$date"
            - write_output m7 "date1=$date"

      - name: micro_build
        type: Bash
        configuration:
          affinityGroup: group1
          inputResources:
            - name: m1
            - name: mgit
        execution: 
          onExecute:
            - echo "Step 2"

      - name: step3
        type: Bash
        configuration:
          affinityGroup: group1
          outputResources:
            - name: m2
          inputSteps:
            - name: micro_build
        execution: 
          onExecute:
            - echo "Step 1"
            - date=$(date)
            - write_output m2 "date1=$date"

      - name: step9
        type: Bash
        configuration:
          inputResources:
            - name: m2
          outputResources:
            - name: m9
            - name: m8
            - name: m10 
        execution: 
          onExecute:
            - echo "Step 4"
            - date=$(date)
            - write_output m9 "date1=$date"
            - write_output m10 "date1=$date"


      - name: step10
        type: Bash
        configuration:
          affinityGroup: group3
          inputResources:
            - name: m6
          inputSteps:
            - name: step9
        execution: 
          onExecute:
            - echo "Step 4"


      - name: step11
        type: Bash
        configuration:
          affinityGroup: group4
          inputResources:
            - name: m7
          outputResources:
            - name: m11
        execution: 
          onExecute:
            - echo "Step 4"
            - date=$(date)
            - write_output m11 "date1=$date"

      - name: step12
        type: Bash
        configuration:
          affinityGroup: group2
          inputResources:
            - name: m7
            - name: m1
          outputResources:
            - name: m3 
        execution: 
          onExecute:
            - echo "Step 4"
            - date=$(date)
            - write_output m3 "date1=$date"

      - name: finish
        type: Bash
        configuration:
          affinityGroup: group2
          inputResources:
            - name: m1
            - name: m2
            - name: m3
            - name: m4
            - name: m5
            - name: m6
            - name: m7
            - name: m8
            - name: m9
            - name: m10
            - name: m11
            - name: m12
        execution: 
          onExecute:
            - echo "Finish"

      
      
  # - name: ResTrig
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m4 "date1=$date"

  # - name: ResTrig1
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"

  # - name: ResTrig3
  #   steps:
  #     - name: trigger
  #       type: Bash
  #       configuration:
  #         affinityGroup: group1
  #         outputResources:
  #           - name: m3
  #           - name: m4
  #       execution: 
  #         onExecute:
  #           - echo "Step 1"
  #           - date=$(date)
  #           - write_output m3 "date1=$date"
  #           - write_output m4 "date1=$date"